# -*- coding: utf-8 -*-
"""IPL 2026 stage 1_Data Loading.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ERqT8A7NSyLvgseJbWC2KJVeo7HbsuT
"""

from google.colab import drive
drive.mount('/content/drive')

print("✅ Drive mounted successfully")

# ============================================
# MASTER RELOAD — Run this every session
# ============================================
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

BASE = '/content/drive/MyDrive/CSK 2026 Analysis/raw data/'

deliveries_2026 = pd.read_csv(BASE + 'ipl_2026_deliveries.csv')
deliveries_2023 = pd.read_csv(BASE + 'ipl_2023_deliveries.csv')
matches         = pd.read_csv(BASE + 'matches.csv')

csk_match_ids = deliveries_2026[
    (deliveries_2026['batting_team'] == 'CSK') |
    (deliveries_2026['bowling_team'] == 'CSK')
]['match_id'].unique()

csk_batting = deliveries_2026[
    (deliveries_2026['match_id'].isin(csk_match_ids)) &
    (deliveries_2026['batting_team'] == 'CSK')
].copy()

csk_bowling = deliveries_2026[
    (deliveries_2026['match_id'].isin(csk_match_ids)) &
    (deliveries_2026['bowling_team'] == 'CSK')
].copy()

results = []
for match_id in sorted(csk_match_ids):
    match = deliveries_2026[
        deliveries_2026['match_id'] == match_id
    ]
    teams = match['batting_team'].unique()
    if len(teams) < 2:
        continue
    team1, team2 = teams[0], teams[1]
    innings1 = match[match['innings'] == 1]
    innings2 = match[match['innings'] == 2]
    score1 = innings1['runs_of_bat'].sum() + innings1['extras'].sum()
    score2 = innings2['runs_of_bat'].sum() + innings2['extras'].sum()
    winner = team2 if score2 > score1 else team1
    if 'CSK' in [team1, team2]:
        csk_result  = 'WIN' if winner == 'CSK' else 'LOSS'
        opponent    = team2 if team1 == 'CSK' else team1
        csk_innings = 1 if team1 == 'CSK' else 2
        csk_score   = score1 if csk_innings == 1 else score2
        opp_score   = score2 if csk_innings == 1 else score1
        csk_wkts    = innings1['player_dismissed'].notna().sum() \
                      if csk_innings == 1 else \
                      innings2['player_dismissed'].notna().sum()
        results.append({
            'match_id'  : match_id,
            'date'      : match['date'].iloc[0],
            'venue'     : match['venue'].iloc[0],
            'opponent'  : opponent,
            'csk_score' : int(csk_score),
            'csk_wkts'  : int(csk_wkts),
            'opp_score' : int(opp_score),
            'result'    : csk_result
        })

csk_results = pd.DataFrame(results)

print("✅ All variables rebuilt")
print(f"   CSK matches    : {len(csk_match_ids)}")
print(f"   Batting rows   : {len(csk_batting):,}")
print(f"   Bowling rows   : {len(csk_bowling):,}")
print(f"   Results table  : {len(csk_results)} matches")

import pandas as pd
import warnings
warnings.filterwarnings('ignore')

BASE = '/content/drive/MyDrive/CSK 2026 Analysis/raw data/'

deliveries_2026 = pd.read_csv(BASE + 'ipl_2026_deliveries.csv')
deliveries_2023 = pd.read_csv(BASE + 'ipl_2023_deliveries.csv')
matches = pd.read_csv(BASE + 'matches.csv')

print("✅ Data loaded successfully")
print(f"2026 deliveries : {len(deliveries_2026):,} rows")
print(f"2023 deliveries : {len(deliveries_2023):,} rows")
print(f"Matches         : {len(matches):,} rows")

print("=" * 55)
print("2026 DELIVERIES — COLUMN NAMES")
print("=" * 55)
for i, col in enumerate(deliveries_2026.columns, 1):
    print(f"  {i:02d}. {col}")

print("All team names in 2026 dataset:")
print(sorted(deliveries_2026['batting_team'].unique()))

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

BASE = '/content/drive/MyDrive/CSK 2026 Analysis/raw data/'

try:
    deliveries_2026 = pd.read_csv(BASE + 'ipl_2026_deliveries.csv')
    print(f"✅ 2026 deliveries : {len(deliveries_2026):,} rows")
except Exception as e:
    print(f"❌ 2026 deliveries failed: {e}")

try:
    deliveries_2023 = pd.read_csv(BASE + 'ipl_2023_deliveries.csv')
    print(f"✅ 2023 deliveries : {len(deliveries_2023):,} rows")
except Exception as e:
    print(f"❌ 2023 deliveries failed: {e}")

try:
    matches = pd.read_csv(BASE + 'matches.csv')
    print(f"✅ Matches         : {len(matches):,} rows")
except Exception as e:
    print(f"❌ Matches failed: {e}")

print("\n📅 Seasons in matches:")
print(matches['season'].value_counts().sort_index())


print("\n📋 Matches columns:")
for i, col in enumerate(matches.columns, 1):
    print(f"   {i:02d}. {col}")

print("\n🏏 Teams in 2026:")
print(sorted(deliveries_2026['batting_team'].unique()))

print("Matches columns:")
for i, col in enumerate(matches.columns, 1):
    print(f"   {i:02d}. {col}")

print("\nMatches sample — first 3 rows:")
print(matches.head(3).to_string())

csk_matches = matches[
    (matches['team1'] == 'CSK') |
    (matches['team2'] == 'CSK')
].copy()

print(f"✅ CSK total matches: {len(csk_matches)}")

wins   = len(csk_matches[csk_matches['match_winner'] == 'CSK'])
losses = len(csk_matches[csk_matches['match_winner'] != 'CSK'])

print(f"   Wins   : {wins}")
print(f"   Losses : {losses}")

print(f"\n📍 Venues CSK played:")
print(csk_matches['venue'].value_counts())

csk_match_ids = csk_matches['match_id'].tolist()

csk_batting = deliveries_2026[
    (deliveries_2026['match_id'].isin(csk_match_ids)) &
    (deliveries_2026['batting_team'] == 'CSK')
].copy()

csk_bowling = deliveries_2026[
    (deliveries_2026['match_id'].isin(csk_match_ids)) &
    (deliveries_2026['bowling_team'] == 'CSK')
].copy()

print(f"\n✅ CSK batting deliveries : {len(csk_batting):,}")
print(f"✅ CSK bowling deliveries : {len(csk_bowling):,}")

print("\n⚠️  Null check — CSK batting:")
key_cols = ['striker', 'bowler', 'runs_of_bat',
            'over', 'wicket_type', 'player_dismissed']
for col in key_cols:
    nulls = csk_batting[col].isnull().sum()
    status = "✅" if nulls == 0 else "⚠️ "
    print(f"   {status} {col}: {nulls} nulls")

print("Sample match_ids from matches table:")
print(csk_matches['match_id'].head(5).tolist())

print("\nSample match_ids from deliveries:")
print(deliveries_2026['match_id'].head(5).tolist())

print(f"\nmatches match_id type   : {matches['match_id'].dtype}")
print(f"deliveries match_id type: {deliveries_2026['match_id'].dtype}")

overlap = set(csk_matches['match_id']).intersection(
    set(deliveries_2026['match_id'])
)
print(f"\nOverlapping match IDs: {len(overlap)}")
print(f"Sample overlap: {list(overlap)[:3]}")

sample_match = deliveries_2026[
    deliveries_2026['match_id'] == 202601
]

print(f"Rows in match 202601: {len(sample_match)}")
print(f"\nTeams:")
print(sample_match['batting_team'].unique())

print(f"\nVenue:")
print(sample_match['venue'].unique())

print(f"\nDate:")
print(sample_match['date'].unique())

print(f"\nInnings:")
print(sample_match['innings'].unique())

all_matches = deliveries_2026['match_id'].unique()
print(f"\nTotal unique matches in deliveries: {len(all_matches)}")
print(f"All match IDs: {sorted(all_matches)}")

csk_match_ids = deliveries_2026[
    (deliveries_2026['batting_team'] == 'CSK') |
    (deliveries_2026['bowling_team'] == 'CSK')
]['match_id'].unique()

print(f"✅ CSK match IDs found: {len(csk_match_ids)}")
print(f"   Match IDs: {sorted(csk_match_ids)}")

csk_batting = deliveries_2026[
    (deliveries_2026['match_id'].isin(csk_match_ids)) &
    (deliveries_2026['batting_team'] == 'CSK')
].copy()

csk_bowling = deliveries_2026[
    (deliveries_2026['match_id'].isin(csk_match_ids)) &
    (deliveries_2026['bowling_team'] == 'CSK')
].copy()

print(f"\n✅ CSK batting deliveries : {len(csk_batting):,}")
print(f"✅ CSK bowling deliveries : {len(csk_bowling):,}")

print(f"\n📊 CSK matches played: {len(csk_match_ids)}")

csk_all = deliveries_2026[
    deliveries_2026['match_id'].isin(csk_match_ids)
]
venues = csk_all.groupby('match_id')['venue'].first()
print(f"\n📍 Venues CSK played:")
print(venues.value_counts())

dates = csk_all.groupby('match_id')['date'].first()
print(f"\n📅 CSK match dates:")
print(dates.values)

results = []

for match_id in sorted(csk_match_ids):
    match = deliveries_2026[
        deliveries_2026['match_id'] == match_id
    ]


    teams = match['batting_team'].unique()
    if len(teams) < 2:
        continue

    team1, team2 = teams[0], teams[1]


    innings1 = match[match['innings'] == 1]
    innings2 = match[match['innings'] == 2]

    score1 = innings1['runs_of_bat'].sum() + innings1['extras'].sum()
    score2 = innings2['runs_of_bat'].sum() + innings2['extras'].sum()

    wkts1 = innings1['player_dismissed'].notna().sum()
    wkts2 = innings2['player_dismissed'].notna().sum()

    if score2 > score1:
        winner = team2
    elif score1 > score2:
        winner = team1
    else:
        winner = 'Tie'

    date  = match['date'].iloc[0]
    venue = match['venue'].iloc[0]


    if 'CSK' in [team1, team2]:
        csk_result = 'WIN' if winner == 'CSK' else 'LOSS'
        opponent   = team2 if team1 == 'CSK' else team1

        csk_innings = 1 if team1 == 'CSK' else 2
        opp_innings = 2 if team1 == 'CSK' else 1

        csk_score = score1 if csk_innings == 1 else score2
        opp_score = score2 if csk_innings == 1 else score1
        csk_wkts  = wkts1  if csk_innings == 1 else wkts2

        results.append({
            'match_id'  : match_id,
            'date'      : date,
            'venue'     : venue,
            'opponent'  : opponent,
            'csk_score' : int(csk_score),
            'csk_wkts'  : int(csk_wkts),
            'opp_score' : int(opp_score),
            'result'    : csk_result
        })

csk_results = pd.DataFrame(results)

print("=" * 65)
print("CSK IPL 2026 — MATCH BY MATCH RESULTS")
print("=" * 65)
print(csk_results[[
    'date','opponent','csk_score',
    'csk_wkts','opp_score','result'
]].to_string(index=False))

print(f"\n{'='*65}")
wins   = len(csk_results[csk_results['result'] == 'WIN'])
losses = len(csk_results[csk_results['result'] == 'LOSS'])
print(f"WINS: {wins}   LOSSES: {losses}   TOTAL: {len(csk_results)}")

print("CSK WICKET FALL PATTERN — 2026")
print("=" * 60)

for match_id in sorted(csk_match_ids):
    match_bat = csk_batting[
        csk_batting['match_id'] == match_id
    ]

    date = match_bat['date'].iloc[0]

    opponent = deliveries_2026[
        (deliveries_2026['match_id'] == match_id) &
        (deliveries_2026['batting_team'] != 'CSK')
    ]['batting_team'].iloc[0]

    wickets = match_bat[
        match_bat['player_dismissed'].notna()
    ][['over','player_dismissed']].copy()

    total_wkts = len(wickets)
    result = csk_results[
        csk_results['match_id'] == match_id
    ]['result'].values[0]

    print(f"\n{date} vs {opponent} | "
          f"Wickets: {total_wkts} | {result}")

    if len(wickets) > 0:
        for _, row in wickets.iterrows():
            print(f"  Over {int(row['over']):02d} → "
                  f"{row['player_dismissed']}")

powerplay_analysis = []

for match_id in sorted(csk_match_ids):
    match_bat = csk_batting[
        csk_batting['match_id'] == match_id
    ]

    pp_wickets = match_bat[
        (match_bat['player_dismissed'].notna()) &
        (match_bat['over'] <= 5)
    ]

    post_pp_wickets = match_bat[
        (match_bat['player_dismissed'].notna()) &
        (match_bat['over'] > 5)
    ]

    pp_runs = match_bat[
        match_bat['over'] <= 5
    ]['runs_of_bat'].sum()

    total_wkts = match_bat['player_dismissed'].notna().sum()

    result = csk_results[
        csk_results['match_id'] == match_id
    ]['result'].values[0]


    date = match_bat['date'].iloc[0]
    opponent = deliveries_2026[
        (deliveries_2026['match_id'] == match_id) &
        (deliveries_2026['batting_team'] != 'CSK')
    ]['batting_team'].iloc[0]

    powerplay_analysis.append({
        'match_id'      : match_id,
        'date'          : date,
        'opponent'      : opponent,
        'pp_wickets'    : len(pp_wickets),
        'pp_runs'       : int(pp_runs),
        'total_wickets' : int(total_wkts),
        'result'        : result
    })

pp_df = pd.DataFrame(powerplay_analysis)

print("CSK POWERPLAY ANALYSIS — 2026")
print("=" * 65)
print(pp_df[[
    'date','opponent','pp_wickets',
    'pp_runs','total_wickets','result'
]].to_string(index=False))

print("\n" + "=" * 65)
print("SUMMARY BY RESULT")
print(pp_df.groupby('result')[
    ['pp_wickets','pp_runs','total_wickets']
].mean().round(2))

print("\n" + "=" * 65)
print("MATCHES WITH 0-1 POWERPLAY WICKETS:")
low_pp = pp_df[pp_df['pp_wickets'] <= 1]
wins   = len(low_pp[low_pp['result'] == 'WIN'])
losses = len(low_pp[low_pp['result'] == 'LOSS'])
print(f"Wins: {wins}  Losses: {losses}")

print("\nMATCHES WITH 3+ POWERPLAY WICKETS:")
high_pp = pp_df[pp_df['pp_wickets'] >= 3]
wins2   = len(high_pp[high_pp['result'] == 'WIN'])
losses2 = len(high_pp[high_pp['result'] == 'LOSS'])
print(f"Wins: {wins2}  Losses: {losses2}")

pp_dismissals = csk_batting[
    (csk_batting['player_dismissed'].notna()) &
    (csk_batting['over'] <= 5)
][['match_id','date','over',
   'player_dismissed','bowler']].copy()

print("CSK POWERPLAY DISMISSALS — 2026")
print("=" * 55)
print(f"Total powerplay wickets lost: {len(pp_dismissals)}")
print()

player_pp_dismissals = pp_dismissals[
    'player_dismissed'
].value_counts()

print("DISMISSALS PER PLAYER IN POWERPLAY:")
print("-" * 40)
for player, count in player_pp_dismissals.items():
    bar = "█" * count
    print(f"  {player:<25} {count}  {bar}")

print("\n" + "=" * 55)
print("SAMSON POWERPLAY DISMISSAL IMPACT:")
print("-" * 40)

samson_pp_out = pp_dismissals[
    pp_dismissals['player_dismissed'] == 'Sanju Samson'
]['match_id'].tolist()

samson_pp_survived = [
    m for m in csk_match_ids
    if m not in samson_pp_out
]

out_results = csk_results[
    csk_results['match_id'].isin(samson_pp_out)
]['result'].value_counts()

survived_results = csk_results[
    csk_results['match_id'].isin(samson_pp_survived)
]['result'].value_counts()

print(f"Matches Samson OUT in powerplay: {len(samson_pp_out)}")
print(f"Results: {dict(out_results)}")
print()
print(f"Matches Samson SURVIVED powerplay: {len(samson_pp_survived)}")
print(f"Results: {dict(survived_results)}")

print("\n" + "=" * 55)
print("RUTURAJ POWERPLAY DISMISSAL IMPACT:")
print("-" * 40)

ruturaj_pp_out = pp_dismissals[
    pp_dismissals['player_dismissed'] == 'Ruturaj Gaikwad'
]['match_id'].tolist()

ruturaj_survived = [
    m for m in csk_match_ids
    if m not in ruturaj_pp_out
]

out_results_r = csk_results[
    csk_results['match_id'].isin(ruturaj_pp_out)
]['result'].value_counts()

survived_results_r = csk_results[
    csk_results['match_id'].isin(ruturaj_survived)
]['result'].value_counts()

print(f"Matches Ruturaj OUT in powerplay: {len(ruturaj_pp_out)}")
print(f"Results: {dict(out_results_r)}")
print()
print(f"Matches Ruturaj SURVIVED powerplay: {len(ruturaj_survived)}")
print(f"Results: {dict(survived_results_r)}")

print("RUTURAJ GAIKWAD — 2026 BATTING PROFILE")
print("=" * 65)

ruturaj_stats = []

for match_id in sorted(csk_match_ids):
    match_bat = csk_batting[
        csk_batting['match_id'] == match_id
    ]

    ruturaj = match_bat[
        match_bat['striker'] == 'Ruturaj Gaikwad'
    ]

    if len(ruturaj) == 0:
        continue

    balls   = len(ruturaj[ruturaj['wide'] == 0])
    runs    = ruturaj['runs_of_bat'].sum()
    sr      = round((runs / balls * 100), 1) if balls > 0 else 0

    dismissed = match_bat[
        match_bat['player_dismissed'] == 'Ruturaj Gaikwad'
    ]
    out_over = int(dismissed['over'].iloc[0]) if len(dismissed) > 0 else 20

    if out_over <= 5:
        phase = 'POWERPLAY'
    elif out_over <= 14:
        phase = 'MIDDLE'
    else:
        phase = 'DEATH'

    date   = match_bat['date'].iloc[0]
    result = csk_results[
        csk_results['match_id'] == match_id
    ]['result'].values[0]

    if balls >= 15 and sr < 120 and phase == 'MIDDLE':
        flag = '⚠️  RESOURCE WASTE'
    elif balls >= 20 and sr >= 140:
        flag = '✅ IMPACT INNINGS'
    elif out_over <= 5:
        flag = '❌ EARLY DISMISSAL'
    else:
        flag = ''

    ruturaj_stats.append({
        'date'    : date,
        'balls'   : balls,
        'runs'    : int(runs),
        'sr'      : sr,
        'out_over': out_over,
        'phase'   : phase,
        'result'  : result,
        'flag'    : flag
    })

    print(f"{date} | {int(runs):>3} off {balls:>2} balls "
          f"| SR: {sr:>6} | Out: over {out_over:>2} "
          f"| {result} | {flag}")

rdf = pd.DataFrame(ruturaj_stats)

print("\n" + "=" * 65)
print("RUTURAJ SUMMARY BY RESULT:")
print(rdf.groupby('result')[['balls','runs','sr']].mean().round(1))

print("\nRESOURCE WASTE INNINGS:")
waste = rdf[rdf['flag'] == '⚠️  RESOURCE WASTE']
print(f"Count: {len(waste)} out of {len(rdf)} innings")
print(waste[['date','balls','runs','sr','result']])

print("SANJU SAMSON — 2026 BATTING PROFILE")
print("=" * 65)

samson_stats = []

for match_id in sorted(csk_match_ids):
    match_bat = csk_batting[
        csk_batting['match_id'] == match_id
    ]

    samson = match_bat[
        match_bat['striker'] == 'Sanju Samson'
    ]

    if len(samson) == 0:
        continue

    balls  = len(samson[samson['wide'] == 0])
    runs   = samson['runs_of_bat'].sum()
    sr     = round((runs / balls * 100), 1) if balls > 0 else 0

    dismissed = match_bat[
        match_bat['player_dismissed'] == 'Sanju Samson'
    ]
    out_over = int(dismissed['over'].iloc[0]) \
               if len(dismissed) > 0 else 20

    phase = 'POWERPLAY' if out_over <= 5 else \
            'MIDDLE' if out_over <= 14 else 'DEATH'

    date   = match_bat['date'].iloc[0]
    result = csk_results[
        csk_results['match_id'] == match_id
    ]['result'].values[0]

    # Contribution flag
    if runs >= 30 and sr >= 140:
        flag = '✅ IMPACT'
    elif out_over <= 2 and runs <= 10:
        flag = '❌ FAILED'
    elif balls >= 15 and sr < 110:
        flag = '⚠️  SLOW'
    else:
        flag = ''

    samson_stats.append({
        'date'    : date,
        'balls'   : balls,
        'runs'    : int(runs),
        'sr'      : sr,
        'out_over': out_over,
        'phase'   : phase,
        'result'  : result,
        'flag'    : flag
    })

    print(f"{date} | {int(runs):>3} off {balls:>2} balls "
          f"| SR: {sr:>6} | Out: over {out_over:>2} "
          f"| {result} | {flag}")

sdf = pd.DataFrame(samson_stats)

print("\n" + "=" * 65)
print("SAMSON SUMMARY BY RESULT:")
print(sdf.groupby('result')[['balls','runs','sr']].mean().round(1))

print("\n" + "=" * 65)
print("SLOW INNINGS:")
slow = sdf[sdf['flag'] == '⚠️  SLOW']
print(f"Count: {len(slow)} out of {len(sdf)} innings")
print(slow[['date','balls','runs','sr','result']])
impact = sdf[sdf['flag'] == '✅ IMPACT']
failed = sdf[sdf['flag'] == '❌ FAILED']
print(f"Impact innings (30+ runs, 140+ SR): {len(impact)}")
print(f"Failed innings (out by over 2, under 10 runs): {len(failed)}")
print(f"\nWhen Samson has IMPACT innings:")
print(impact[['date','runs','sr','result']])

print("SHIVAM DUBE — PHASE BY PHASE ANALYSIS")
print("=" * 60)

dube_phase = []

for match_id in sorted(csk_match_ids):
    match_bat = csk_batting[
        csk_batting['match_id'] == match_id
    ]

    dube = match_bat[match_bat['striker'] == 'Shivam Dube']

    if len(dube) == 0:
        continue

    pp   = dube[dube['over'] <= 5]
    mid  = dube[(dube['over'] > 5) & (dube['over'] <= 14)]
    death = dube[dube['over'] >= 15]

    def phase_stats(df):
        balls = len(df[df['wide'] == 0])
        runs  = df['runs_of_bat'].sum()
        sr    = round(runs/balls*100, 1) if balls > 0 else 0
        return int(balls), int(runs), sr

    pp_b,    pp_r,    pp_sr    = phase_stats(pp)
    mid_b,   mid_r,   mid_sr   = phase_stats(mid)
    death_b, death_r, death_sr = phase_stats(death)

    total_balls = pp_b + mid_b + death_b
    total_runs  = pp_r + mid_r + death_r

    dismissed = match_bat[
        match_bat['player_dismissed'] == 'Shivam Dube'
    ]
    out_over = int(dismissed['over'].iloc[0]) \
               if len(dismissed) > 0 else 20

    date   = match_bat['date'].iloc[0]
    result = csk_results[
        csk_results['match_id'] == match_id
    ]['result'].values[0]

    dube_phase.append({
        'date'    : date,
        'total'   : f"{total_runs} off {total_balls}",
        'pp_sr'   : pp_sr,
        'mid_sr'  : mid_sr,
        'death_sr': death_sr,
        'death_b' : death_b,
        'out_over': out_over,
        'result'  : result
    })

    print(f"{date} | Total: {total_runs:>3} off {total_balls:>2} "
          f"| PP SR: {pp_sr:>6} "
          f"| Mid SR: {mid_sr:>6} "
          f"| Death SR: {death_sr:>6} "
          f"({death_b} balls) | {result}")

ddf = pd.DataFrame(dube_phase)

print("\n" + "=" * 60)
print("DUBE AVERAGE STRIKE RATE BY PHASE:")
print(f"  Powerplay SR  : {ddf['pp_sr'].mean():.1f}")
print(f"  Middle SR     : {ddf['mid_sr'].mean():.1f}")
print(f"  Death SR      : {ddf['death_sr'].mean():.1f}")

print("\n" + "=" * 60)
print("DUBE IN DEATH OVERS (15-20):")
death_innings = ddf[ddf['death_b'] > 0]
print(f"Innings with death over balls: {len(death_innings)}")
print(f"Average death SR: {death_innings['death_sr'].mean():.1f}")
print(f"Average death balls faced: {death_innings['death_b'].mean():.1f}")

wins_death  = death_innings[death_innings['result']=='WIN']
loss_death  = death_innings[death_innings['result']=='LOSS']
print(f"\nWhen Dube bats in death — Wins: {len(wins_death)} Losses: {len(loss_death)}")

print("BOWLER PRESENCE IMPACT ON RESULTS")
print("=" * 60)

bowlers_to_check = [
    'Akeal Hosein',
    'Jamie Overton',
]

for bowler in bowlers_to_check:
    played    = []
    not_played = []

    for match_id in sorted(csk_match_ids):
        match_bowl = csk_bowling[
            csk_bowling['match_id'] == match_id
        ]

        result = csk_results[
            csk_results['match_id'] == match_id
        ]['result'].values[0]

        bowler_bowled = bowler in \
            match_bowl['bowler'].unique()

        if bowler_bowled:
            played.append(result)
        else:
            not_played.append(result)

    played_wins    = played.count('WIN')
    played_losses  = played.count('LOSS')
    absent_wins    = not_played.count('WIN')
    absent_losses  = not_played.count('LOSS')

    played_wr  = round(played_wins/len(played)*100) \
                 if played else 0
    absent_wr  = round(absent_wins/len(not_played)*100) \
                 if not_played else 0

    print(f"\n{bowler}:")
    print(f"  Matches played : {len(played)}")
    print(f"  Wins / Losses  : {played_wins}W {played_losses}L")
    print(f"  Win rate       : {played_wr}%")
    print(f"\n  Matches absent : {len(not_played)}")
    print(f"  Wins / Losses  : {absent_wins}W {absent_losses}L")
    print(f"  Win rate       : {absent_wr}%")

print("\n" + "=" * 60)
print("WHEN BOTH AKEAL + OVERTON PLAY TOGETHER:")
print("-" * 40)

both_played   = []
either_absent = []

for match_id in sorted(csk_match_ids):
    match_bowl = csk_bowling[
        csk_bowling['match_id'] == match_id
    ]

    result = csk_results[
        csk_results['match_id'] == match_id
    ]['result'].values[0]

    bowlers = match_bowl['bowler'].unique()

    akeal_played   = 'Akeal Hosein' in bowlers
    overton_played = 'Jamie Overton' in bowlers

    if akeal_played and overton_played:
        both_played.append({
            'result': result,
            'match_id': match_id
        })
    else:
        either_absent.append({
            'result'         : result,
            'akeal_played'   : akeal_played,
            'overton_played' : overton_played,
            'match_id'       : match_id
        })

both_wins   = sum(1 for m in both_played
                  if m['result'] == 'WIN')
both_losses = sum(1 for m in both_played
                  if m['result'] == 'LOSS')
both_wr     = round(both_wins/len(both_played)*100) \
              if both_played else 0

absent_wins_c   = sum(1 for m in either_absent
                      if m['result'] == 'WIN')
absent_losses_c = sum(1 for m in either_absent
                      if m['result'] == 'LOSS')
absent_wr_c     = round(absent_wins_c/
                        len(either_absent)*100) \
                  if either_absent else 0

print(f"Both played    : {len(both_played)} matches")
print(f"Wins / Losses  : {both_wins}W {both_losses}L")
print(f"Win rate       : {both_wr}%")

print(f"\nEither absent  : {len(either_absent)} matches")
print(f"Wins / Losses  : {absent_wins_c}W {absent_losses_c}L")
print(f"Win rate       : {absent_wr_c}%")

print("\nMatches where Akeal OR Overton was absent:")
for m in either_absent:
    date = csk_bowling[
        csk_bowling['match_id'] == m['match_id']
    ]['date'].iloc[0]
    opponent = deliveries_2026[
        (deliveries_2026['match_id'] == m['match_id']) &
        (deliveries_2026['batting_team'] != 'CSK')
    ]['batting_team'].iloc[0]
    print(f"  {date} vs {opponent} "
          f"| Akeal: {'✅' if m['akeal_played'] else '❌'} "
          f"| Overton: {'✅' if m['overton_played'] else '❌'} "
          f"| {m['result']}")

print("CSK 2026 — COMPLETE BOWLER ANALYSIS")
print("=" * 70)

all_bowlers = csk_bowling['bowler'].unique()

bowler_stats = []

for bowler in all_bowlers:
    bowler_data = csk_bowling[
        csk_bowling['bowler'] == bowler
    ]

    legal = bowler_data[
        (bowler_data['wide'] == 0) &
        (bowler_data['noballs'] == 0)
    ]

    balls      = len(legal)
    overs      = round(balls / 6, 1)
    runs       = (bowler_data['runs_of_bat'].sum() +
                  bowler_data['wide'].sum() +
                  bowler_data['noballs'].sum())
    wickets    = bowler_data[
        bowler_data['player_dismissed'].notna()
    ]['player_dismissed'].count()

    economy    = round(runs / overs, 2) if overs > 0 else 0
    avg        = round(runs / wickets, 1) if wickets > 0 else 999
    sr_bowl    = round(balls / wickets, 1) if wickets > 0 else 999

    pp    = bowler_data[bowler_data['over'] <= 5]
    mid   = bowler_data[
        (bowler_data['over'] > 5) &
        (bowler_data['over'] <= 14)
    ]
    death = bowler_data[bowler_data['over'] >= 15]

    def econ(df):
        b = len(df[(df['wide']==0) & (df['noballs']==0)])
        r = (df['runs_of_bat'].sum() +
             df['wide'].sum() +
             df['noballs'].sum())
        ov = b / 6
        return round(r/ov, 2) if ov > 0 else 0

    pp_econ    = econ(pp)
    mid_econ   = econ(mid)
    death_econ = econ(death)

    if overs >= 5:
        bowler_stats.append({
            'bowler'     : bowler,
            'overs'      : overs,
            'wickets'    : int(wickets),
            'runs'       : int(runs),
            'economy'    : economy,
            'average'    : avg,
            'SR'         : sr_bowl,
            'pp_econ'    : pp_econ,
            'mid_econ'   : mid_econ,
            'death_econ' : death_econ
        })

bdf = pd.DataFrame(bowler_stats).sort_values(
    'wickets', ascending=False
)

print(f"\n{'Bowler':<20} {'Overs':>6} {'Wkts':>5} "
      f"{'Econ':>6} {'Avg':>6} {'SR':>6} "
      f"{'PP Eco':>7} {'Mid Eco':>8} {'Death Eco':>10}")
print("-" * 80)

for _, row in bdf.iterrows():
    print(f"{row['bowler']:<20} {row['overs']:>6} "
          f"{row['wickets']:>5} {row['economy']:>6} "
          f"{row['average']:>6} {row['SR']:>6} "
          f"{row['pp_econ']:>7} {row['mid_econ']:>8} "
          f"{row['death_econ']:>10}")

print("\n" + "=" * 70)
print("FOCUS: KAMBOJ vs AKEAL vs OVERTON")
print("-" * 70)

focus = bdf[bdf['bowler'].isin([
    'Anshul Kamboj',
    'Akeal Hosein',
    'Jamie Overton'
])]

for _, row in focus.iterrows():
    print(f"\n{row['bowler']}")
    print(f"  Wickets  : {row['wickets']}")
    print(f"  Economy  : {row['economy']}")
    print(f"  Average  : {row['average']}")
    print(f"  PP Econ  : {row['pp_econ']}")
    print(f"  Mid Econ : {row['mid_econ']}")
    print(f"  Death Econ: {row['death_econ']}")

print("ANSHUL KAMBOJ — MATCH BY MATCH FORM")
print("=" * 65)

kamboj_timeline = []

for i, match_id in enumerate(sorted(csk_match_ids), 1):
    match_bowl = csk_bowling[
        csk_bowling['match_id'] == match_id
    ]

    kamboj = match_bowl[
        match_bowl['bowler'] == 'Anshul Kamboj'
    ]

    if len(kamboj) == 0:
        continue

    legal   = kamboj[
        (kamboj['wide'] == 0) &
        (kamboj['noballs'] == 0)
    ]
    balls   = len(legal)
    overs   = round(balls/6, 1)
    runs    = (kamboj['runs_of_bat'].sum() +
               kamboj['wide'].sum() +
               kamboj['noballs'].sum())
    wickets = kamboj[
        kamboj['player_dismissed'].notna()
    ]['player_dismissed'].count()
    economy = round(runs/overs, 2) if overs > 0 else 0

    date   = match_bowl['date'].iloc[0]
    result = csk_results[
        csk_results['match_id'] == match_id
    ]['result'].values[0]

    if economy <= 8.5:
        flag = '✅ GOOD'
    elif economy <= 10.0:
        flag = '⚠️  AVERAGE'
    else:
        flag = '❌ EXPENSIVE'

    kamboj_timeline.append({
        'match_no' : i,
        'date'     : date,
        'overs'    : overs,
        'wickets'  : int(wickets),
        'runs'     : int(runs),
        'economy'  : economy,
        'result'   : result,
        'flag'     : flag
    })

    print(f"Match {i:>2} | {date} | "
          f"{overs}ov {int(wickets)}wkt "
          f"Econ: {economy:>6} | "
          f"{result} | {flag}")

ktdf = pd.DataFrame(kamboj_timeline)

first_half  = ktdf[ktdf['match_no'] <= 7]
second_half = ktdf[ktdf['match_no'] > 7]

print("\n" + "=" * 65)
print("FIRST HALF vs SECOND HALF:")
print(f"  First 7 matches  — Avg economy: "
      f"{first_half['economy'].mean():.2f} | "
      f"Wickets: {first_half['wickets'].sum()}")
print(f"  Last 7 matches   — Avg economy: "
      f"{second_half['economy'].mean():.2f} | "
      f"Wickets: {second_half['wickets'].sum()}")

print("NO.3 POSITION ANALYSIS — MHATRE vs URVIL")
print("=" * 65)

def player_analysis(player_name, label):
    print(f"\n{'─'*65}")
    print(f"{label}: {player_name}")
    print(f"{'─'*65}")

    stats = []

    for match_id in sorted(csk_match_ids):
        match_bat = csk_batting[
            csk_batting['match_id'] == match_id
        ]

        player = match_bat[
            match_bat['striker'] == player_name
        ]

        if len(player) == 0:
            continue

        entry_over = int(player['over'].iloc[0])

        balls = len(player[player['wide'] == 0])
        runs  = player['runs_of_bat'].sum()
        sr    = round(runs/balls*100, 1) if balls > 0 else 0

        fours  = len(player[player['runs_of_bat'] == 4])
        sixes  = len(player[player['runs_of_bat'] == 6])
        dots   = len(player[
            (player['runs_of_bat'] == 0) &
            (player['wide'] == 0)
        ])
        dot_pct = round(dots/balls*100, 1) if balls > 0 else 0

        dismissed = match_bat[
            match_bat['player_dismissed'] == player_name
        ]
        out_over = int(dismissed['over'].iloc[0]) \
                   if len(dismissed) > 0 else 20

        date   = match_bat['date'].iloc[0]
        result = csk_results[
            csk_results['match_id'] == match_id
        ]['result'].values[0]

        if runs >= 25 and sr >= 130:
            flag = '✅ IMPACT'
        elif balls >= 10 and sr < 100:
            flag = '⚠️  SLOW'
        elif balls <= 6 and runs <= 8:
            flag = '❌ FAILED'
        else:
            flag = ''

        stats.append({
            'date'      : date,
            'entry'     : entry_over,
            'runs'      : int(runs),
            'balls'     : balls,
            'sr'        : sr,
            'fours'     : fours,
            'sixes'     : sixes,
            'dot_pct'   : dot_pct,
            'out_over'  : out_over,
            'result'    : result,
            'flag'      : flag
        })

        print(f"{date} | "
              f"Entered: {entry_over:>2} | "
              f"{int(runs):>3} off {balls:>2} | "
              f"SR: {sr:>6} | "
              f"Dots: {dot_pct:>5}% | "
              f"4s:{fours} 6s:{sixes} | "
              f"{result} | {flag}")

    if not stats:
        print("  No innings found")
        return

    df = pd.DataFrame(stats)

    print(f"\n  SUMMARY")
    print(f"  {'─'*40}")
    print(f"  Matches          : {len(df)}")
    print(f"  Total runs       : {df['runs'].sum()}")
    print(f"  Average runs     : {df['runs'].mean():.1f}")
    print(f"  Average SR       : {df['sr'].mean():.1f}")
    print(f"  Average dot %    : {df['dot_pct'].mean():.1f}%")
    print(f"  Impact innings   : "
          f"{len(df[df['flag']=='✅ IMPACT'])}")
    print(f"  Failed innings   : "
          f"{len(df[df['flag']=='❌ FAILED'])}")
    print(f"  Slow innings     : "
          f"{len(df[df['flag']=='⚠️  SLOW'])}")

    print(f"\n  RESULTS WHEN BATTING:")
    print(f"  Wins  : "
          f"{len(df[df['result']=='WIN'])}")
    print(f"  Losses: "
          f"{len(df[df['result']=='LOSS'])}")

    return df

mhatre_df = player_analysis(
    'Ayush Mhatre',
    'FIRST HALF NO.3'
)

urvil_df = player_analysis(
    'Urvil Patel',
    'SECOND HALF NO.3'
)

print("\n" + "=" * 65)
print("HEAD TO HEAD COMPARISON — NO.3 POSITION")
print("=" * 65)

metrics = [
    ('Matches played',
     len(mhatre_df), len(urvil_df)),
    ('Total runs',
     mhatre_df['runs'].sum(),
     urvil_df['runs'].sum()),
    ('Average runs',
     round(mhatre_df['runs'].mean(),1),
     round(urvil_df['runs'].mean(),1)),
    ('Average SR',
     round(mhatre_df['sr'].mean(),1),
     round(urvil_df['sr'].mean(),1)),
    ('Average dot %',
     round(mhatre_df['dot_pct'].mean(),1),
     round(urvil_df['dot_pct'].mean(),1)),
    ('Impact innings',
     len(mhatre_df[mhatre_df['flag']=='✅ IMPACT']),
     len(urvil_df[urvil_df['flag']=='✅ IMPACT'])),
    ('Failed innings',
     len(mhatre_df[mhatre_df['flag']=='❌ FAILED']),
     len(urvil_df[urvil_df['flag']=='❌ FAILED'])),
    ('Wins when batting',
     len(mhatre_df[mhatre_df['result']=='WIN']),
     len(urvil_df[urvil_df['result']=='WIN'])),
]

print(f"\n{'Metric':<22} {'Mhatre':>10} {'Urvil':>10}  {'Better':>8}")
print("─" * 55)

for metric, m_val, u_val in metrics:

    if metric in ['Average dot %', 'Failed innings']:
        better = 'Mhatre' if m_val < u_val else \
                 'Urvil' if u_val < m_val else 'Equal'
    else:
        better = 'Mhatre' if m_val > u_val else \
                 'Urvil' if u_val > m_val else 'Equal'

    print(f"{metric:<22} {str(m_val):>10} "
          f"{str(u_val):>10}  {better:>8}")

print("\n" + "=" * 65)
print("VERDICT:")
mhatre_wins = sum(
    1 for _, _, m, u, _ in
    [(metric, None,
      (m_val > u_val),
      (u_val > m_val),
      None)
     for metric, m_val, u_val in metrics
     if metric not in
     ['Average dot %','Failed innings']]
    if m
)

print("SARFARAZ KHAN — BATTING ENTRY POSITIONS")
print("=" * 55)

sarfaraz_entries = []

for match_id in sorted(csk_match_ids):
    match_bat = csk_batting[
        csk_batting['match_id'] == match_id
    ]

    sarfaraz = match_bat[
        match_bat['striker'] == 'Sarfaraz Khan'
    ]

    if len(sarfaraz) == 0:
        continue

    entry_over = sarfaraz['over'].iloc[0]
    balls = len(sarfaraz[sarfaraz['wide'] == 0])
    runs  = sarfaraz['runs_of_bat'].sum()
    sr    = round(runs/balls*100, 1) if balls > 0 else 0

    dismissed = match_bat[
        match_bat['player_dismissed'] == 'Sarfaraz Khan'
    ]
    out_over = int(dismissed['over'].iloc[0]) \
               if len(dismissed) > 0 else 20

    date   = match_bat['date'].iloc[0]
    result = csk_results[
        csk_results['match_id'] == match_id
    ]['result'].values[0]

    if entry_over <= 5:
        phase = 'POWERPLAY'
    elif entry_over <= 14:
        phase = 'MIDDLE'
    else:
        phase = 'DEATH'

    sarfaraz_entries.append({
        'date'       : date,
        'entry_over' : int(entry_over),
        'phase'      : phase,
        'runs'       : int(runs),
        'balls'      : balls,
        'sr'         : sr,
        'out_over'   : out_over,
        'result'     : result
    })

    print(f"{date} | Entered over {int(entry_over):>2} "
          f"({phase:<10}) | "
          f"{int(runs):>3} off {balls:>2} "
          f"SR: {sr:>6} | {result}")

sdf = pd.DataFrame(sarfaraz_entries)

print("\n" + "=" * 55)
print("ENTRY PHASE BREAKDOWN:")
print(sdf['phase'].value_counts())
print(f"\nEntry over range: {sdf['entry_over'].min()} "
      f"to {sdf['entry_over'].max()}")
print(f"Standard deviation: "
      f"{sdf['entry_over'].std():.1f}")
print("\nAverage SR by entry phase:")
print(sdf.groupby('phase')['sr'].mean().round(1))

SAVE = '/content/drive/MyDrive/CSK 2026 Analysis/cleaned data/'

csk_batting.to_csv(SAVE + 'csk_batting_2026.csv', index=False)
csk_bowling.to_csv(SAVE + 'csk_bowling_2026.csv', index=False)
csk_results.to_csv(SAVE + 'csk_results_2026.csv', index=False)

print("✅ All files saved. Python stage complete.")

